name: galleryze
description: A modern gallery app that organizes device photos into customizable categories.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  cached_network_image: ^3.3.0
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.1.0
  path: ^1.8.3
  flutter_image_compress: ^2.0.0
  flutter_cache_manager: ^3.3.1
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - test/
  
  # Add custom fonts, images, etc
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
